Repository hyperledger-labs/fabric-smart-client, pull requests merged in 2022-11, with the labels that each got.

#430 fix delivery restart
  platform/fabric/core/generic/delivery/delivery.go
Labels: bug

#431 keys are sanitised directly by orion, no need for extra sanitization
  integration/orion/cars/views/transfer.go
  platform/orion/core/generic/session.go
  platform/orion/driver/sm.go
  platform/orion/services/db/orion.go
  platform/orion/services/otx/loaded.go
  platform/orion/transaction.go
Labels: cleanup

#439 key validation removal
  platform/fabric/core/generic/vault/rwset.go
  platform/fabric/services/weaver/relay/fabric/rwset.go
  platform/orion/core/generic/vault/rwset.go
Labels: bug

#436 various enhancements
  integration/fabric/atsa/chaincode/topology.go
  integration/fabric/atsa/fsc/topology.go
  integration/fabric/events/chaincode/topology.go
  integration/fabric/fpc/echo/topology.go
  integration/fabric/iou/topology.go
  integration/fabric/iouhsm/topology.go
  integration/fabric/iouorionbe/topology.go
  integration/fabric/stoprestart/topology.go
  integration/fabric/twonets/topology.go
  integration/fabric/weaver/relay/topology.go
  integration/nwo/cmd/cryptogen/ca/ca.go
  integration/nwo/cmd/cryptogen/cryptogen.go
  integration/nwo/cmd/cryptogen/msp/msp.go
  integration/nwo/cmd/cryptogen/msp/msp_test.go
  integration/nwo/common/context/context.go
  integration/nwo/fsc/node/node_template.go
  integration/nwo/fsc/node/org.go
  integration/nwo/fsc/testdata/main/main.go.output
  integration/nwo/fsc/topology.go
  platform/fabric/core/driver.go
  platform/fabric/core/generic/config/ds.go
  platform/fabric/core/generic/driver/driver.go
  platform/fabric/core/generic/fabricutils/pr.go
  platform/fabric/core/generic/fabricutils/utils.go
  platform/fabric/core/generic/msp/driver/driver.go
  platform/fabric/core/generic/msp/idemix/cache.go
  platform/fabric/core/generic/msp/idemix/cache_test.go
  platform/fabric/core/generic/msp/idemix/loader.go
  platform/fabric/core/generic/msp/mock/config_provider.go
  platform/fabric/core/generic/msp/service.go
  platform/fabric/core/generic/msp/x509/loader.go
  platform/fabric/core/generic/msp/x509/provider.go
  platform/fabric/core/generic/msp/x509/setup.go
  platform/fabric/core/generic/ordering/ordering.go
  platform/fabric/core/generic/transaction/pr.go
  platform/fabric/core/generic/transaction/transasction.go
  platform/fabric/core/provider.go
  platform/fabric/driver/driver.go
  platform/fabric/driver/transaction.go
  platform/fabric/sdk/sdk.go
  platform/fabric/services/endorser/builder.go
  platform/fabric/services/endorser/endorsement_proposal.go
  platform/fabric/services/endorser/transaction.go
  platform/fabric/transaction.go
  platform/view/core/manager/context.go
  platform/view/core/manager/manager.go
  platform/view/driver/flowmanager.go
  platform/view/manager.go
  platform/view/sdk/sdk.go
  platform/view/services/kvs/kvs.go
  platform/view/services/session/json.go
  samples/fabric/iou/topology/topology.go
  samples/fabric/weaver/relay/topology/topology.go
Labels: enhancement
