Repository hyperledger-labs/fabric-smart-client, pull requests merged in 2022-09, with the labels that each got.

#388 Add timeout to Finality API #380
  integration/fabric/iou/views/approver.go
  integration/fabric/iou/views/borrower.go
  integration/fabric/iou/views/lender.go
  pkg/api/client.go
  pkg/node/node.go
  platform/fabric/core/generic/chaincode/invoke.go
  platform/fabric/core/generic/chaincode/support.go
  platform/fabric/core/generic/committer/committer.go
  platform/fabric/core/generic/finality.go
  platform/fabric/core/generic/finality/finality.go
  platform/fabric/core/generic/finality/view.go
  platform/fabric/core/generic/peer/peer.go
  platform/fabric/core/views/finality.go
  platform/fabric/driver/finality.go
  platform/fabric/finality.go
  platform/fabric/services/endorser/finality.go
  platform/fabric/services/endorser/ordering.go
  platform/fabric/services/state/finality.go
  platform/fabric/services/state/ordering.go
  platform/orion/core/generic/committer/committer.go
  platform/orion/core/generic/finality/finality.go
  platform/orion/driver/finality.go
  platform/orion/finality.go
  platform/orion/services/db/driver.go
  platform/view/sdk/finality/handler.go
  platform/view/services/db/driver/badger/badger.go
  platform/view/services/session/json.go
Labels: enhancement

#387 Unit tests mocks cleanup #368
  platform/fabric/core/generic/id/info_test.go
  platform/fabric/core/generic/msp/idemix/provider_test.go
  platform/view/services/kvs/kvs.go
  platform/view/services/kvs/kvs_test.go
  platform/view/services/kvs/mock/config_provider.go
Labels: cleanup

#390 view comm layer: override ip address #389
  platform/view/core/endpoint/endpoint.go
  platform/view/services/comm/io/conn_test.go
  platform/view/services/comm/p2p.go
  platform/view/services/comm/p2p_test.go
  platform/view/services/comm/session.go
Labels: enhancement, node-p2p

#392 if no default MSP is set, pick the first
  platform/fabric/core/generic/msp/service.go
Labels: enhancement

#394 minor enhancements
  integration/integration.go
  integration/nwo/fabric/network/checks.go
  integration/nwo/orion/platform.go
  platform/fabric/chaincode.go
  platform/fabric/core/generic/rwset/envelope.go
  platform/fabric/core/generic/transaction/envelope.go
  platform/fabric/driver/transaction.go
  platform/orion/core/generic/transaction/manager.go
  platform/orion/driver/transaction.go
  platform/orion/transaction.go
Labels: enhancement

#396 go1.18
  Makefile
  go.mod
  platform/view/services/grpc/creds_test.go
  tools/go.mod
Labels: enhancement

#399 Minor updates to IOU sample README and code for simplicity and clarity
  samples/fabric/iou/.gitignore
  samples/fabric/iou/README.md
  samples/fabric/iou/views/approver.go
Labels: documentation
