Repository hyperledger-labs/fabric-smart-client, pull requests merged in 2023-02, with the labels that each got.

#447 Support for multiple key management mechanisms
  platform/view/core/id/provider.go
  platform/view/core/id/provider_test.go
  platform/view/sdk/sdk.go
  platform/view/services/db/driver/driver.go
  platform/view/services/kms/driver/driver.go
  platform/view/services/kms/driver/file/driver.go
  platform/view/services/kms/kms.go
Labels: enhancement

#454 Nwo enhancements
  integration/nwo/api/api.go
  integration/nwo/common/context/context.go
  integration/nwo/fabric/network/checks.go
  integration/nwo/fabric/network/network.go
  integration/nwo/fabric/network/network_support.go
  integration/nwo/fabric/topology/configtx_template.go
  integration/nwo/fabric/topology/core_template.go
  integration/nwo/fabric/topology/crypto_template.go
  integration/nwo/fabric/topology/orderer_template.go
  integration/nwo/fsc/fsc.go
Labels: enhancement

#453 various improvements
  integration/nwo/fsc/node/core_template.go
  platform/fabric/core/generic/transaction/services.go
  platform/fabric/core/generic/vault/mocks/config.go
  platform/fabric/core/generic/vault/txidstore/mocks/config.go
  platform/fabric/core/generic/vault/txidstore/simpletxidstore_test.go
  platform/fabric/core/generic/vault/vault_test.go
  platform/fabric/fns.go
  platform/orion/core/generic/vault/mocks/config.go
  platform/orion/core/generic/vault/simpletxidstore_test.go
  platform/view/services/db/config.go
  platform/view/services/db/db.go
  platform/view/services/db/driver/badger/badger.go
  platform/view/services/db/driver/badger/badger_test.go
  platform/view/services/db/driver/badger/bench_test.go
  platform/view/services/db/driver/badger/config.go
  platform/view/services/db/driver/badger/driver.go
  platform/view/services/db/driver/driver.go
  platform/view/services/db/driver/unversioned/mocks/config.go
  platform/view/services/db/driver/unversioned/unversioned_test.go
  platform/view/services/kvs/kvs.go
  platform/view/services/kvs/kvs_test.go
Labels: enhancement

#455 Fixes in orderer yaml template
  integration/nwo/fabric/topology/orderer_template.go
Labels: bug

#459 Changes in templates for re-usability of NWO
  integration/integration.go
  integration/nwo/fabric/topology/core_template.go
  integration/nwo/fsc/fsc.go
  integration/nwo/fsc/node/core_template.go
  integration/nwo/fsc/resolver.go
  integration/nwo/fsc/templates.go
  integration/nwo/fsc/topology.go
  platform/view/core/endpoint/endpoint.go
Labels: enhancement

#464 core-fabric update with the new tracing section
  docs/core-fabric.md
Labels: documentation
