Repository hyperledger-labs/fabric-smart-client, pull requests merged in 2024-12, with the labels that each got.

#703 Created ScanBlock method to allow for custom and more efficient uses …
  platform/fabric/core/generic/delivery/delivery.go
  platform/fabric/core/generic/delivery/service.go
  platform/fabric/delivery.go
  platform/fabric/driver/delivery.go
Labels: improvement

#706 Removed pq dependencies
  go.mod
  go.sum
  integration/nwo/fsc/node/node_template.go
  platform/common/utils/collections/iterators.go
  platform/common/utils/encode.go
  platform/view/services/db/dbtest/helpers.go
  platform/view/services/db/driver/notifier/persistence.go
  platform/view/services/db/driver/sql/common/test_utils.go
  platform/view/services/db/driver/sql/common/unversioned.go
  platform/view/services/db/driver/sql/common/versioned.go
  platform/view/services/db/driver/sql/postgres/base.go
  platform/view/services/db/driver/sql/postgres/encode.go
  platform/view/services/db/driver/sql/postgres/errormapper.go
  platform/view/services/db/driver/sql/postgres/notifier.go
  platform/view/services/db/driver/sql/postgres/persistence.go
  platform/view/services/db/driver/sql/postgres/sql_test.go
  platform/view/services/db/driver/sql/postgres/test_utils.go
  platform/view/services/db/driver/sql/postgres/unversioned.go
  platform/view/services/db/driver/sql/postgres/versioned.go
  platform/view/services/db/driver/sql/sqlite/sql_test.go
Labels: improvement

#662 update deps in chaincode go modules
  integration/fabric/weaver/relay/chaincode/go.mod
  integration/fabric/weaver/relay/chaincode/go.sum
  platform/fabric/services/state/cc/query/go.mod
  platform/fabric/services/state/cc/query/go.sum
  platform/fabric/services/state/cc/query/main.go
Labels: dependencies

#713 add configurable maxIdleConns and maxIdleTime for sql databases
  docs/core-fabric.md
  platform/common/core/generic/vault/db/helpers.go
  platform/view/services/db/dbtest/bench.go
  platform/view/services/db/driver/badger/badger.go
  platform/view/services/db/driver/driver.go
  platform/view/services/db/driver/notifier/persistence.go
  platform/view/services/db/driver/sql/common/base.go
  platform/view/services/db/driver/sql/common/utils.go
  platform/view/services/db/driver/sql/common/versioned.go
  platform/view/services/db/driver/sql/postgres/bench_test.go
  platform/view/services/db/driver/sql/postgres/persistence.go
  platform/view/services/db/driver/sql/postgres/sql_test.go
  platform/view/services/db/driver/sql/postgres/test_utils.go
  platform/view/services/db/driver/sql/postgres/unversioned.go
  platform/view/services/db/driver/sql/postgres/versioned.go
  platform/view/services/db/driver/sql/sqlite/persistence.go
  platform/view/services/db/driver/sql/sqlite/unversioned.go
  platform/view/services/db/driver/sql/sqlite/versioned.go
  platform/view/services/db/driver/unversioned/unversioned.go
Labels: improvement

#711 fix race condition
  platform/view/services/comm/p2p.go
Labels: bug

#721 chore: fix some function names in comment
  platform/fabric/core/generic/msp/x509/ecdsa.go
  platform/view/services/grpc/connection.go
  platform/view/services/grpc/creds.go
  platform/view/services/grpc/tlsgen/ca.go
Labels: documentation
