Repository hyperledger-labs/fabric-smart-client, pull requests merged in 2025-05, with the labels that each got.

#904 Refactored comm service
  platform/view/services/comm/comm.go
  platform/view/services/comm/host/host.go
  platform/view/services/comm/host/libp2p/conn_test.go
  platform/view/services/comm/host/libp2p/p2p_test.go
  platform/view/services/comm/host/libp2p/provider.go
  platform/view/services/comm/host/rest/client.go
  platform/view/services/comm/host/rest/config.go
  platform/view/services/comm/host/rest/host.go
  platform/view/services/comm/host/rest/p2p_test.go
  platform/view/services/comm/host/rest/provider.go
  platform/view/services/comm/host/rest/server.go
  platform/view/services/comm/host/rest/websocket/multiplexed_provider.go
  platform/view/services/comm/provider/provider.go
Labels: enhancement

#905 Extensible client/server TLS config
  platform/view/services/comm/host/rest/config.go
  platform/view/services/comm/host/rest/host.go
  platform/view/services/comm/host/rest/p2p_test.go
  platform/view/services/comm/host/rest/provider.go
Labels: configuration

#916 Add context to AuditInfoStore #915
  docs/db-driver.md
  platform/common/driver/kvs.go
  platform/common/driver/sigservice.go
  platform/common/services/sig/service.go
  platform/view/services/db/driver/sql/common/auditinfo.go
  platform/view/sig.go
Labels: enhancement

#859 Replace itiai10/copy with built-in os.copyFS
  go.mod
  go.sum
  platform/fabric/core/generic/msp/service_test.go
Labels: dependencies
