Repository hyperledger-labs/fabric-smart-client, pull requests merged in 2025-07, with the labels that each got.

#972 fix: send on closed channel in delivery #970
  platform/fabric/core/generic/delivery/delivery.go
Labels: bug

#983 Fix postgres container health-check
  platform/view/services/storage/driver/sql/postgres/test_utils.go
Labels: db

#989 NWO: disable profiling by default
  README.md
  integration/nwo/fsc/fsc.go
Labels: NWO

#971 fix: get / set current context in manager #969
  platform/view/services/view/manager.go
  platform/view/services/view/manager_test.go
Labels: bug

#986 Clean up logging
  pkg/node/node.go
  platform/common/core/generic/committer/finality.go
  platform/fabric/core/config.go
  platform/fabric/core/generic/config/service.go
  platform/fabric/core/generic/delivery/delivery.go
  platform/fabric/core/generic/events/listenermanager.go
  platform/fabric/core/generic/msp/idemix/cache.go
  platform/fabric/core/generic/msp/idemix/id.go
  platform/fabric/core/generic/ordering/bft.go
  platform/fabric/fns.go
  platform/fabric/services/db/driver/sql/common/vault.go
  platform/view/services/comm/host/rest/routing/idrouter.go
  platform/view/services/comm/host/rest/server.go
  platform/view/services/comm/host/rest/websocket/multiplexed_provider_test.go
  platform/view/services/grpc/logging/server.go
  platform/view/services/metrics/operations/system.go
  platform/view/services/storage/driver/notifier/notifier.go
  platform/view/services/storage/driver/sql/common/auditinfo.go
  platform/view/services/storage/driver/sql/common/signerinfo.go
  platform/view/services/storage/driver/sql/common/simplekeydata.go
  platform/view/services/storage/driver/sql/common/unversioned.go
  platform/view/services/storage/driver/sql/postgres/binding.go
  platform/view/services/storage/driver/sql/postgres/errormapper.go
  platform/view/services/storage/driver/sql/postgres/notifier.go
  platform/view/services/storage/driver/sql/postgres/persistence.go
  platform/view/services/storage/driver/sql/sqlite/binding.go
  platform/view/services/storage/driver/sql/sqlite/errormapper.go
  platform/view/services/storage/driver/sql/sqlite/retrywritedb.go
  platform/view/services/storage/kvs/kvs.go
  platform/view/services/view/grpc/server/server.go
  platform/view/services/view/grpc/server/view.go
  platform/view/services/view/manager.go
  platform/view/services/view/web/dispatcher.go
  platform/view/services/web/client/wsclient.go
  platform/view/services/web/server/handler.go
  platform/view/services/web/server/stream.go
Labels: cleanup, perf

#994 Tame ignore error logging
  integration/nwo/common/runner/runner.go
  platform/common/utils/closer.go
Labels: cleanup

#990 NWO: Bring back nwo race detector
  integration/fabric/atsa/chaincode/atsa_test.go
  integration/fabric/atsa/fsc/atsa_test.go
  integration/fabric/events/chaincode/events_test.go
  integration/fabric/iou/iou_test.go
  integration/fabric/iouhsm/iou_test.go
  integration/fabric/stoprestart/stoprestart_test.go
  integration/fsc/pingpong/pingpong_test.go
  integration/fsc/stoprestart/stoprestart_test.go
  integration/integration.go
  integration/nwo/common/builder.go
Labels: NWO

#995 fabric-sdk: sequential events
  platform/fabric/core/generic/events/listenermanager.go
Labels: improvement
