Repository hyperledger-labs/fabric-smart-client, pull requests merged in 2025-08, with the labels that each got.

#1007 added keyset pagination serialization
  platform/common/driver/pagination.go
  platform/fabric/services/storage/vault/vaultstore_test.go
  platform/view/services/storage/driver/sql/query/common/types.go
  platform/view/services/storage/driver/sql/query/pagination/interpreter.go
  platform/view/services/storage/driver/sql/query/pagination/keyset.go
  platform/view/services/storage/driver/sql/query/pagination/keyset_test.go
  platform/view/services/storage/driver/sql/query/pagination/none.go
  platform/view/services/storage/driver/sql/query/pagination/none_test.go
  platform/view/services/storage/driver/sql/query/pagination/offset.go
  platform/view/services/storage/driver/sql/query/pagination/page.go
  platform/view/services/storage/driver/sql/query/select/query.go
Labels: db

#1012 metrics harmonization: Add subsystem to metricsOpts and derive prams from path
  docs/platform/view/monitoring.md
  integration/fabric/iou/commands.go
  integration/reporting/prometheus/client.go
  platform/common/core/generic/committer/finality.go
  platform/common/core/generic/committer/listenermgr.go
  platform/common/core/generic/vault/metrics.go
  platform/common/core/generic/vault/vault.go
  platform/fabric/core/generic/committer/committer.go
  platform/fabric/core/generic/committer/metrics.go
  platform/fabric/core/generic/delivery/delivery.go
  platform/fabric/core/generic/metrics/metrics.go
  platform/view/services/comm/host/libp2p/metrics.go
  platform/view/services/comm/host/rest/websocket/metrics.go
  platform/view/services/comm/host/rest/websocket/multiplexed_provider.go
  platform/view/services/comm/metrics.go
  platform/view/services/grpc/metrics.go
  platform/view/services/metrics/prometheus/provider.go
  platform/view/services/tracing/config.go
  platform/view/services/tracing/config_test.go
  platform/view/services/tracing/provider.go
  platform/view/services/view/grpc/client/client.go
  platform/view/services/view/grpc/client/local.go
  platform/view/services/view/grpc/server/metrics.go
  platform/view/services/view/grpc/server/server.go
  platform/view/services/view/grpc/server/view.go
  platform/view/services/view/manager.go
  platform/view/services/view/metrics.go
  platform/view/services/view/web/view.go
Labels: documentation, enhancement, cleanup

#1017 drop statsd support
  docs/core-fabric.md
  docs/platform/view/monitoring.md
  integration/fsc/pingpong/testdata/fsc/nodes/initiator.0/core.yaml
  integration/fsc/pingpong/testdata/fsc/nodes/responder.0/core.yaml
  integration/nwo/fabric/fabricconfig/core.go
  integration/nwo/fabric/fabricconfig/orderer.go
  integration/nwo/fabric/network/network.go
  integration/nwo/fabric/topology/core_template.go
  integration/nwo/fabric/topology/orderer_template.go
  integration/nwo/fsc/node/core_template.go
  platform/fabric/core/generic/metrics/metrics.go
  platform/view/sdk/dig/servers.go
  platform/view/services/comm/host/libp2p/metrics.go
  platform/view/services/comm/host/rest/websocket/metrics.go
  platform/view/services/comm/metrics.go
  platform/view/services/metrics/internal/namer/namer.go
  platform/view/services/metrics/internal/namer/namer_suite_test.go
  platform/view/services/metrics/internal/namer/namer_test.go
  platform/view/services/metrics/operations/metrics.go
  platform/view/services/metrics/operations/system.go
  platform/view/services/metrics/operations/system_test.go
  platform/view/services/metrics/prometheus/provider_test.go
  platform/view/services/metrics/provider.go
  platform/view/services/metrics/statsd/goruntime/collector.go
  platform/view/services/metrics/statsd/goruntime/collector_test.go
  platform/view/services/metrics/statsd/goruntime/goruntime_suite_test.go
  platform/view/services/metrics/statsd/goruntime/metrics.go
  platform/view/services/metrics/statsd/provider.go
  platform/view/services/metrics/statsd/provider_test.go
  platform/view/services/metrics/statsd/statsd_suite_test.go
  platform/view/services/tracing/provider.go
  platform/view/services/view/grpc/server/metrics.go
  platform/view/services/view/metrics.go
Labels: cleanup

#1019 otel: sanitize event strings #1018
  docs/core-fabric.md
  integration/nwo/fsc/node/core_template.go
  integration/nwo/fsc/topology.go
  integration/nwo/fsc/topology_test.go
  platform/common/services/logging/config.go
  platform/common/services/logging/logger.go
  platform/common/services/logging/otel.go
  platform/common/services/logging/types.go
  platform/common/services/logging/types_test.go
  platform/view/services/config/provider.go
Labels: enhancement, configuration

#1024 GetLedgerInfo() always fails #1023
  platform/fabric/core/generic/ledger/ledger.go
Labels: bug
