Repository hyperledger-labs/fabric-smart-client, pull requests merged in 2025-04, with the labels that each got.

#858 Replace ginkgo v1 with v2 everywhere
  go.mod
  go.sum
  platform/view/services/metrics/disabled/disabled_suite_test.go
  platform/view/services/metrics/disabled/provider_test.go
  platform/view/services/metrics/internal/namer/namer_suite_test.go
  platform/view/services/metrics/internal/namer/namer_test.go
  platform/view/services/metrics/prometheus/prometheus_suite_test.go
  platform/view/services/metrics/prometheus/provider_test.go
  platform/view/services/metrics/statsd/goruntime/collector_test.go
  platform/view/services/metrics/statsd/goruntime/goruntime_suite_test.go
  platform/view/services/metrics/statsd/provider_test.go
  platform/view/services/metrics/statsd/statsd_suite_test.go
Labels: testing, dependencies

#861 consistent use of testify
  go.mod
  go.sum
  platform/fabric/core/generic/committer/event_test.go
  platform/fabric/services/state/namespace_test.go
  platform/view/services/assert/assert.go
  platform/view/services/db/driver/sql/common/helpers.go
  platform/view/services/registry/sp_test.go
  platform/view/services/storage/vault/vaultstore_test.go
Labels: dependencies

#865 Replace ttlcache with our own cache
  go.mod
  go.sum
  platform/fabric/core/generic/chaincode/chaincode.go
  platform/fabric/core/generic/chaincode/discovery.go
Labels: dependencies

#862 Fix flaky cache timeout tests
  platform/common/utils/cache/timeout.go
  platform/common/utils/cache/timeout_test.go
Labels: testing

#775 chore: make function comment match function name
  integration/nwo/fabric/network/network_support.go
  integration/nwo/fabric/network/utils.go
Labels: documentation

#887 Add concurrent websocket session test
  platform/view/services/comm/comm_test.go
Labels: testing

#896 fixes to make token-sdk working
  platform/common/utils/cache/eviction.go
Labels: bug
